apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydep
  template:
    metadata:
      labels:
        app: mydep
    spec:
      containers:
      - image: alpine:3.9.6
        command: ["/bin/sh","-c","sleep 10000"]
        imagePullPolicy: Always
        name: mydep
        ports:
        - containerPort: 80