apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: mypod
spec:
  securityContext:
    runAsNonRoot: false
    runAsGroup: 1000
    runAsUser: 1000
  containers:
  - name: mypod
    image: alpine
    command: ["/bin/sh","-c","cat"]
    env:
    - name: ENV_VAR_SECRET
      value: "true"
    ports:
    - name: http
      port: 80
  restartPolicy: Always
