kind: Service
apiVersion: v1
metadata:
  name: mypod-svc
  labels:
    component: controller
spec:
  selector:
    name: mypod
    component: controller
  ports:
  - name: http
    port: 8080
    targetPort: 80
  type: ClusterIP
