apiVersion: v1
kind: Pod
metadata:
  labels:
    component: controller
  name: ${USERNAME}
spec:
  securityContext:
    runAsNonRoot: false
    runAsGroup: 1000
    runAsUser: 1000
  containers:
  - name: mypod
    image: nginx
    env:
    - name: ENV_VAR_SECRET
      value: "true"
    ports:
    - name: http
      port: 80
  restartPolicy: Always
