apiVersion: v1
kind: Pod
metadata:
  labels:
    component: controller
  name: georgec
spec:
  containers:
  - name: mypod
    image: nginx
    env:
    - name: ENV_VAR_SECRET
      value: "true"
    ports:
    - name: http
      containerPort: 80
  restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: georgec-svc
  labels:
    component: controller
spec:
  selector:
    name: georgec
    component: controller
  ports:
  - name: http
    port: 8080
    targetPort: 80
  type: ClusterIP
